server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fachrianlr/config-env.git
          default-label: main
          clone-on-start: true
          force-pull: true